version: '3'

services:
  payment-app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    depends_on:
      - datasource
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}

  datasource:
    image: postgres:16.0-alpine
    container_name: ${DATASOURCE_HOST}
    env_file:
      - "./.env"
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    expose:
      - "5432"