application:
  precision:
    default: 18

  rounding-mode:
    default: HALF_EVEN

server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: purchase-app

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate